// <auto-generated />
using System;
using Curso.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curso.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230905201350_CreateDatabase2")]
    partial class CreateDatabase2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.Property<int>("AlunosIdAlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursosIdCursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunosIdAlunoId", "CursosIdCursoId");

                    b.HasIndex("CursosIdCursoId");

                    b.ToTable("AlunoModelCursoModel");
                });

            modelBuilder.Entity("Curso.RazorPages.Models.AlunoModel", b =>
                {
                    b.Property<int?>("IdAlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInscricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdAlunoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Curso.RazorPages.Models.CursoModel", b =>
                {
                    b.Property<int?>("IdCursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTermino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCursoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.HasOne("Curso.RazorPages.Models.AlunoModel", null)
                        .WithMany()
                        .HasForeignKey("AlunosIdAlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curso.RazorPages.Models.CursoModel", null)
                        .WithMany()
                        .HasForeignKey("CursosIdCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
