// <auto-generated />
using System;
using Curso.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Curso.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.Property<int>("AlunosAlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CursosCursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunosAlunoId", "CursosCursoId");

                    b.HasIndex("CursosCursoId");

                    b.ToTable("AlunoModelCursoModel");
                });

            modelBuilder.Entity("Curso.RazorPages.Models.AlunoModel", b =>
                {
                    b.Property<int?>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInscricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Curso.RazorPages.Models.CursoModel", b =>
                {
                    b.Property<int?>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataTermino")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("AlunoModelCursoModel", b =>
                {
                    b.HasOne("Curso.RazorPages.Models.AlunoModel", null)
                        .WithMany()
                        .HasForeignKey("AlunosAlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Curso.RazorPages.Models.CursoModel", null)
                        .WithMany()
                        .HasForeignKey("CursosCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
